[package]
name = "deadwiki"
version = "0.1.14-dev"
authors = ["chris west <c@xvxx.io>"]
edition = "2018"
license = "MIT"
description = "dead simple personal wiki"
repository = "https://github.com/xvxx/deadwiki"
readme = "README.md"

[[bin]]
name = "dead"
path = "src/main.rs"

[features]
gui = ["web-view"]
default = []

[package.metadata.release]
pre-release-replacements = [
  {file="CHANGELOG.md", search="\\d+\\.\\d+\\.\\d+-dev", replace="{{version}}"},
]
dev-version-ext = "dev"

[dependencies]
vial = { path = "../vial", features = ['horror'] }

pulldown-cmark = { version = "0.7", default-features = false }
autolink = "0.3.0"
walkdir = "2"
atomicwrites = "0.2.5"
rust-embed = "5.2.0"
lazy_static = "1.4"

web-view = { version = "0.5.4", optional = true }
